[ui]
sidebar-width = 26
index-columns = flags:4,name<20%,subject,date>=
render-account-tabs = always
stylesets-dirs = ~/.config/aerc/stylesets
styleset-name = gruvbox

[viewer]
alternatives = text/plain,text/html

[compose]
editor = nvim

[filters]
text/plain = colorize
text/html = html
