#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          2
# https://convertingcolors.com/hex-color-FF00FF.html?search=Hex(FF00FF)
yabai -m config active_window_border_color   0xFF39FF14
#yabai -m config active_window_border_color   0xFF91BAF8
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                0
yabai -m config window_gap                   0

# apps to not manage (ignore)
# yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="Toolbox$" manage=off
yabai -m rule --add app="Simulator$" manage=off
# yabai -m rule --add app="^IntelliJ IDEA$" manage=off
#yabai -m rule --add app="Teams$" manage=off
# yabai -m rule --add app="Android Studio$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
#yabai -m rule --add app="^Messages$" manage=off
#yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add app="^Microsoft Remote Desktop$" manage=off

# yabai -m config external_bar all:32:0


echo "yabai configuration loaded.."


