# based on https://github.com/BrodieRobertson/dotfiles/blob/master/config/alacritty/alacritty.toml
live_config_reload = true
working_directory = "None"

[window]
opacity = 0.6
padding.x = 5
padding.y = 5
decorations = "Buttonless"
# decorations = "Full"
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#36393d"
blue = "#2e4bea"
cyan = "#54d9ff"
green = "#47c930"
magenta = "#cc15ed"
red = "#ce2727"
white = "#dbdbdb"
yellow = "#fff138"

[colors.cursor]
cursor = "#d8dee9"
text = "#191919"

[colors.dim]
black = "#676f78"
blue = "#707fd0"
cyan = "#8adaf1"
green = "#78a670"
magenta = "#c583d0"
red = "#000000"
white = "#e0e3e7"
yellow = "#faf380"

[colors.normal]
black = "#191919"
blue = "#314ad0"
cyan = "#32d0fc"
green = "#40a62f"
magenta = "#b30ad0"
red = "#b02626"
white = "#acadb1"
yellow = "#f2e635"

[colors.primary]
background = "#191919"
foreground = "#d8dee9"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Underline"
unfocused_hollow = true
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"


[font.offset]
x = -1
y = -1

#############################################
#
#  Keyboard Bindings
#
#############################################

# create a new tmux window (command + t)
[[keyboard.bindings]]
key = "T"
mods = "command"
chars = "\u000a\u0063"

# close tmux window (command + w)
[[keyboard.bindings]]
key = "X"
mods = "command"
chars = "\u000ax"

# save vim buffer (command + s)
[[keyboard.bindings]]
key = "S"
mods = "command"
chars = """
\u001b:w
"""


# open Lazygit (command + g)
[[keyboard.bindings]]
key = "G"
mods = "Command"
chars = """
\u001b:Lazygit
"""


#############################################
#   
#   VI mode
#
#############################################

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"


[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi"
mods = "Shift"


[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"


[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

















